language: node_js
matrix:
  include:
    - node_js: "4"
      env: CXX=g++-4.8
    - node_js: "8"
      env: CXX=g++-4.8
    - node_js: "10"
      env: CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
